[project]
name = "sweaters"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "httpx>=0.28.1",
    "playwright>=1.58.0",
    "pre-commit>=4.5.1",
    "ruff>=0.15.0",
    "selectolax>=0.4.6",
    "tqdm>=4.67.3",
]
